function out = get_Q(p,U)
	%GET_Q Auto-generated function from moyra
	%
	%	Created at : Sun Nov 17 16:26:51 2024 
	%	Created with : moyra https://pypi.org/project/moyra/
	%
	%% extract required parameters from structure
	%% create common groups
	%% create output vector
	out = [0;...
		 0;...
		 0;...
		 0;...
		 0;...
		 0;...
		 0];
end