function out = get_inner_Q_RHS(p,U,W,Xb)
	%GET_INNER_Q_RHS Auto-generated function from moyra
	%
	%	Created at : Sat Nov 16 22:38:51 2024 
	%	Created with : moyra https://pypi.org/project/moyra/
	%
	%% extract required parameters from structure
	b_i = p.b_i;
	%% create common groups
	rep_1 = W(3,:).*Xb(2,:);
	rep_2 = Xb(2,:).^4./b_i.^4;
	rep_3 = b_i.^(-3);
	rep_4 = rep_3.*Xb(2,:).^3;
	rep_5 = b_i.^(-2);
	rep_6 = Xb(2,:).^2;
	rep_7 = rep_5.*rep_6;
	%% create output vector
	out = [rep_1 + (-rep_2.*U(4) + rep_3.*rep_6.*U(6).*Xb(1,:) - rep_4.*U(3) + rep_5.*U(5).*Xb(1,:).*Xb(2,:) - rep_7.*U(2)).*W(2,:) + W(4,:);...
		 rep_7.*W(3,:);...
		 rep_4.*W(3,:);...
		 rep_2.*W(3,:);...
		 -rep_1.*rep_5.*Xb(1,:);...
		 -rep_3.*rep_6.*W(3,:).*Xb(1,:);...
		 0.*W(1,:);...
		 0.*W(1,:);...
		 0.*W(1,:);...
		 0.*W(1,:);...
		 0.*W(1,:);...
		 0.*W(1,:);...
		 0.*W(1,:)];
end